create table public.statistics (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  question text not null,
  answer real not null default '0'::real,
  essentiality integer null default 0,
  constraint statistics_pkey primary key (id),
  constraint statistics_question_key unique (question)
) TABLESPACE pg_default;
